"""chat_translate — provider-agnostic chat translation SDK.

DeepL / local-GGUF backends behind one interface, do-not-translate masking,
per-room fan-out + cache, and ingest-time source resolution.
"""

from __future__ import annotations

from .catalog import (
    CatalogResult,
    EntryResult,
    tidy,
    translate_catalog,
    verify,
)
from .chat import (
    ChatTranslator,
    LanguageDetector,
    ViewerTranslateOptions,
    ViewerTranslation,
    create_chat_translator,
)
from .detector import eld_language_detector, to_language_detector
from .fanout import (
    CachedTranslation,
    InMemoryTranslationCache,
    RoomStats,
    RoomTranslation,
    RoomTranslator,
    TranslationCache,
    create_room_translator,
)
from .icu import (
    PLURAL_CATEGORIES,
    SUBMESSAGE_TYPES,
    Argument,
    MaskedIcu,
    TranslateFn,
    arguments_of,
    find_arguments,
    mask_icu,
    missing_plural_categories,
    parse_branches,
    selectors_of,
    translate_icu,
)
from .masking import (
    BRACKET_SENTINELS,
    DEFAULT_RULES,
    DEFAULT_SENTINELS,
    MaskedMessage,
    MaskRule,
    Sentinels,
    make_sentinels,
    mask_non_translatable,
)
from .plurals import (
    PLURAL_EXAMPLES,
    Expansion,
    build_expand_prompt,
    expand_message,
    parse_forms,
)
from .provider import (
    LANGUAGE_NAMES,
    BaseTranslationProvider,
    DeepLConfig,
    DeepLProvider,
    DeploymentConfig,
    Formality,
    LanguageCode,
    LlamaLike,
    LocalGGUFProvider,
    LocalInstructionTunedProvider,
    OllamaConfig,
    OllamaProvider,
    ProviderCapabilities,
    ProviderName,
    TranslateOptions,
    TranslateResult,
    TranslationError,
    TranslationProvider,
    build_instruction_tuned_prompt,
    build_translation_prompt,
    config_from_env,
    create_provider,
    language_name,
)
from .resolve_source import (
    DEFAULT_SHORT_TEXT_LETTERS,
    DEFAULT_SHORT_TEXT_POLICY,
    ConfidenceDetector,
    DetectionResult,
    EldDetectorLike,
    ResolvedSource,
    ResolveSourceOptions,
    ShortTextPolicy,
    SourceProvenance,
    eld_detector,
    letter_count,
    resolve_source,
)
from .review import (
    DEFAULT_CONTEXT,
    ReviewResult,
    Verdict,
    build_review_prompt,
    review_catalog,
    review_entry,
)

__version__ = "0.1.0"

__all__ = [
    "Argument",
    "BRACKET_SENTINELS",
    "BaseTranslationProvider",
    "CachedTranslation",
    "CatalogResult",
    "ChatTranslator",
    "ConfidenceDetector",
    "DEFAULT_CONTEXT",
    "DEFAULT_RULES",
    "DEFAULT_SENTINELS",
    "DEFAULT_SHORT_TEXT_LETTERS",
    "DEFAULT_SHORT_TEXT_POLICY",
    "DeepLConfig",
    "DeepLProvider",
    "DeploymentConfig",
    "DetectionResult",
    "EldDetectorLike",
    "EntryResult",
    "Expansion",
    "Formality",
    "InMemoryTranslationCache",
    "LANGUAGE_NAMES",
    "LanguageCode",
    "LanguageDetector",
    "LlamaLike",
    "LocalGGUFProvider",
    "LocalInstructionTunedProvider",
    "MaskRule",
    "MaskedIcu",
    "MaskedMessage",
    "OllamaConfig",
    "OllamaProvider",
    "PLURAL_CATEGORIES",
    "PLURAL_EXAMPLES",
    "ProviderCapabilities",
    "ProviderName",
    "ResolveSourceOptions",
    "ResolvedSource",
    "ReviewResult",
    "RoomStats",
    "RoomTranslation",
    "RoomTranslator",
    "SUBMESSAGE_TYPES",
    "Sentinels",
    "ShortTextPolicy",
    "SourceProvenance",
    "TranslateFn",
    "TranslateOptions",
    "TranslateResult",
    "TranslationCache",
    "TranslationError",
    "TranslationProvider",
    "Verdict",
    "ViewerTranslateOptions",
    "ViewerTranslation",
    "arguments_of",
    "build_expand_prompt",
    "build_instruction_tuned_prompt",
    "build_review_prompt",
    "build_translation_prompt",
    "config_from_env",
    "create_chat_translator",
    "create_provider",
    "create_room_translator",
    "eld_detector",
    "eld_language_detector",
    "expand_message",
    "find_arguments",
    "language_name",
    "letter_count",
    "make_sentinels",
    "mask_icu",
    "mask_non_translatable",
    "missing_plural_categories",
    "parse_branches",
    "parse_forms",
    "resolve_source",
    "review_catalog",
    "review_entry",
    "selectors_of",
    "tidy",
    "to_language_detector",
    "translate_catalog",
    "translate_icu",
    "verify",
]
